/**
 * @file ethercat_config.h
 * @brief EtherCAT Plugin Configuration Structures and Parser Interface
 *
 * Defines the C structures that mirror the JSON configuration contract
 * generated by the OpenPLC Editor. The JSON is parsed using cJSON and
 * mapped into these structures for use by the EtherCAT master.
 */

#ifndef ETHERCAT_CONFIG_H
#define ETHERCAT_CONFIG_H

#include <stdbool.h>
#include <stdint.h>

/* Maximum sizes */
#define ECAT_MAX_SLAVES      64
#define ECAT_MAX_CHANNELS    64
#define ECAT_MAX_PDO_ENTRIES 32
#define ECAT_MAX_PDOS        16
#define ECAT_MAX_SDOS        32
#define ECAT_MAX_NAME_LEN    64
#define ECAT_MAX_IEC_LOC_LEN 16

/**
 * @brief Recognized EtherCAT/CoE data types
 *
 * Covers integer, floating-point, and padding types found in PDO entries.
 * REAL32 and REAL64 are transported through the existing DWORD/LWORD buffers
 * (IEEE 754 bit patterns preserved by memcpy).
 */
typedef enum {
    ECAT_DTYPE_UNKNOWN,
    ECAT_DTYPE_BOOL,
    ECAT_DTYPE_INT8,
    ECAT_DTYPE_UINT8,
    ECAT_DTYPE_INT16,
    ECAT_DTYPE_UINT16,
    ECAT_DTYPE_INT32,
    ECAT_DTYPE_UINT32,
    ECAT_DTYPE_INT64,
    ECAT_DTYPE_UINT64,
    ECAT_DTYPE_REAL32,
    ECAT_DTYPE_REAL64,
    ECAT_DTYPE_PAD
} ecat_data_type_t;

/* Error codes */
#define ECAT_CONFIG_OK              0
#define ECAT_CONFIG_ERR_FILE       -1
#define ECAT_CONFIG_ERR_PARSE      -2
#define ECAT_CONFIG_ERR_MEMORY     -3
#define ECAT_CONFIG_ERR_INVALID    -4
#define ECAT_CONFIG_ERR_MISSING    -5

/**
 * @brief PDO entry definition
 *
 * Represents a single entry within a PDO (Process Data Object).
 * Entries with index "0x0000" are padding entries.
 */
typedef struct {
    char             index[12];        /* hex string e.g. "0x6000" */
    uint8_t          subindex;
    uint8_t          bit_length;
    char             name[ECAT_MAX_NAME_LEN];
    char             data_type[12];    /* "BOOL", "INT16", "REAL", etc. */
    ecat_data_type_t parsed_type;      /* enum resolved from data_type string */
} ecat_pdo_entry_t;

/**
 * @brief PDO (Process Data Object) definition
 *
 * Contains the PDO index and its list of entries.
 * RxPDOs are written to the slave, TxPDOs are read from the slave.
 */
typedef struct {
    char             index[12];  /* hex string e.g. "0x1A00" */
    char             name[ECAT_MAX_NAME_LEN];
    ecat_pdo_entry_t entries[ECAT_MAX_PDO_ENTRIES];
    int              entry_count;
} ecat_pdo_t;

/**
 * @brief SDO configuration entry
 *
 * Defines an SDO (Service Data Object) parameter to be written
 * to a slave during configuration phase.
 */
typedef struct {
    char             index[12];        /* hex string e.g. "0x8000" */
    uint8_t          subindex;
    double           value;            /* stored as double; cast to target type at write time */
    char             data_type[12];
    ecat_data_type_t parsed_type;      /* enum resolved from data_type string */
    char             name[ECAT_MAX_NAME_LEN];
} ecat_sdo_config_t;

/**
 * @brief Channel mapping definition
 *
 * Maps a physical I/O channel to an IEC 61131-3 located variable.
 * Links the channel to its corresponding PDO entry.
 */
typedef struct {
    int      index;
    char     name[ECAT_MAX_NAME_LEN];
    char     type[20];         /* "digital_input", "analog_output", etc. */
    uint8_t  bit_length;
    char     iec_location[ECAT_MAX_IEC_LOC_LEN];
    char     pdo_index[12];
    char     pdo_entry_index[12];
    uint8_t  pdo_entry_subindex;
} ecat_channel_t;

/**
 * @brief Per-slave startup checks
 *
 * Controls which identity fields are validated against the SOEM slave list
 * during topology verification.
 */
typedef struct {
    bool     check_vendor_id;
    bool     check_product_code;
} ecat_startup_checks_t;

/**
 * @brief Per-slave addressing
 *
 * Controls slave addressing on the bus.
 */
typedef struct {
    uint16_t ethercat_address;    /* 0 = auto-assign */
} ecat_addressing_t;

/**
 * @brief Per-slave timeouts
 *
 * Configurable timeouts for SDO operations and state transitions.
 */
typedef struct {
    int      sdo_timeout_ms;           /* SDO operation timeout (default: 1000) */
    int      init_to_preop_timeout_ms; /* INIT->PRE-OP timeout (default: 3000) */
    int      safeop_to_op_timeout_ms;  /* SAFE-OP->OP timeout (default: 10000) */
} ecat_timeouts_t;

/**
 * @brief Per-slave watchdog configuration
 *
 * Controls Sync Manager and PDI watchdog behavior per slave.
 */
typedef struct {
    bool     sm_watchdog_enabled;      /* Sync Manager watchdog */
    int      sm_watchdog_ms;           /* SM watchdog timeout (default: 100) */
    bool     pdi_watchdog_enabled;     /* PDI watchdog */
    int      pdi_watchdog_ms;          /* PDI watchdog timeout (default: 100) */
} ecat_watchdog_t;

/**
 * @brief Per-slave Distributed Clocks configuration
 *
 * Controls DC SYNC0/SYNC1 signal generation per slave.
 */
typedef struct {
    bool     enabled;
    int      sync_unit_cycle_us;       /* 0 = use master cycle */
    bool     sync0_enabled;
    int      sync0_cycle_us;
    int      sync0_shift_us;
    bool     sync1_enabled;
    int      sync1_cycle_us;
    int      sync1_shift_us;
} ecat_dc_config_t;

/**
 * @brief EtherCAT slave configuration
 *
 * Complete configuration for a single EtherCAT slave device,
 * including identity, channel mappings, PDOs, SDOs, and per-slave
 * settings for timeouts, watchdogs, and distributed clocks.
 */
typedef struct {
    int               position;        /* ec_slave[position] in SOEM (1-based) */
    char              name[ECAT_MAX_NAME_LEN];
    char              type[20];        /* "coupler", "digital_input", etc. */
    uint32_t          vendor_id;
    uint32_t          product_code;
    uint32_t          revision;
    ecat_channel_t    channels[ECAT_MAX_CHANNELS];
    int               channel_count;
    ecat_sdo_config_t sdo_configs[ECAT_MAX_SDOS];
    int               sdo_count;
    ecat_pdo_t        rx_pdos[ECAT_MAX_PDOS];
    int               rx_pdo_count;
    ecat_pdo_t        tx_pdos[ECAT_MAX_PDOS];
    int               tx_pdo_count;
    ecat_startup_checks_t startup_checks;
    ecat_addressing_t     addressing;
    ecat_timeouts_t       timeouts;
    ecat_watchdog_t       watchdog;
    ecat_dc_config_t      dc;
} ecat_slave_t;

/**
 * @brief Master configuration parameters
 */
/** Maximum interface name length including null terminator.
 *  Linux names fit in IFNAMSIZ (16), but Windows NPF device paths such as
 *  \\Device\\NPF_{GUID} can reach ~55 characters. */
#define ECAT_IFNAME_MAX 128

typedef struct {
    char             interface[ECAT_IFNAME_MAX];
    int              cycle_time_us;
    int              receive_timeout_us;
    int              watchdog_timeout_cycles;
    char             log_level[8];
    char             task_name[ECAT_MAX_NAME_LEN];
    int              task_cycle_time_us;
} ecat_master_config_t;

/**
 * @brief Diagnostics configuration
 */
typedef struct {
    bool             log_connections;
    bool             log_data_access;
    bool             log_errors;
    int              max_log_entries;
    int              status_update_interval_ms;
} ecat_diagnostics_config_t;

/**
 * @brief Top-level EtherCAT configuration
 *
 * Contains the master settings, flat list of slaves, and diagnostics config.
 *
 * WARNING: This struct is approximately 7 MB due to the inline slave array
 * with nested PDOs. It must be allocated statically or on the heap -- never
 * on the stack, as it would overflow most thread stacks.
 */
typedef struct {
    ecat_master_config_t      master;
    ecat_slave_t              slaves[ECAT_MAX_SLAVES];
    int                       slave_count;
    ecat_diagnostics_config_t diagnostics;
} ecat_config_t;

/**
 * @brief Parse EtherCAT configuration from a JSON file
 *
 * Reads and parses the JSON configuration file generated by the OpenPLC Editor.
 * The JSON has an array root format: [{ name, protocol, config }].
 * The "config" object is extracted and mapped to the ecat_config_t structure.
 *
 * @param config_path Path to the JSON configuration file
 * @param config Output configuration structure
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_parse(const char *config_path, ecat_config_t *config);

/**
 * @brief Validate a parsed configuration
 *
 * Checks required fields, value ranges, and IEC location format.
 *
 * @param config Configuration to validate
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_validate(const ecat_config_t *config);

/**
 * @brief Initialize configuration with default values
 *
 * @param config Configuration structure to initialize
 */
void ecat_config_init_defaults(ecat_config_t *config);

/**
 * @brief Parse a data type string into the corresponding enum value
 *
 * Recognizes standard CoE/EtherCAT type names and common aliases:
 *   "BOOL", "INT8"/"SINT", "UINT8"/"USINT", "INT16"/"INT",
 *   "UINT16"/"UINT", "INT32"/"DINT", "UINT32"/"UDINT",
 *   "INT64"/"LINT", "UINT64"/"ULINT",
 *   "REAL"/"REAL32"/"FLOAT", "LREAL"/"REAL64"/"DOUBLE", "PAD"
 *
 * @param str  NUL-terminated data type string (case-insensitive)
 * @return Matching ecat_data_type_t, or ECAT_DTYPE_UNKNOWN if unrecognized
 */
ecat_data_type_t ecat_parse_data_type(const char *str);

/*
 * =============================================================================
 * Plugin State Machine
 * =============================================================================
 */

/** Maximum number of recovery attempts before transitioning to ERROR state */
#define ECAT_MAX_RECOVERY_ATTEMPTS  5

/** Number of consecutive WKC errors before triggering recovery */
#define ECAT_WKC_ERROR_THRESHOLD    3

/**
 * Enable the background monitor thread for slave state checking and recovery.
 * When enabled, a low-priority thread periodically calls ecx_readstate() and
 * attempt_recovery() outside the PLC scan cycle, preventing overruns.
 * When disabled, no state monitoring or automatic recovery is performed
 * at runtime (the bus runs open-loop after reaching OPERATIONAL).
 *
 * Define to 0 to disable, 1 to enable.
 */
#ifndef ECAT_ENABLE_MONITOR_THREAD
#define ECAT_ENABLE_MONITOR_THREAD  1
#endif

/** Background monitor thread polling interval in milliseconds */
#define ECAT_MONITOR_INTERVAL_MS    500

/** Timeout in ms to wait for PLC thread to yield SOEM access */
#define ECAT_SOEM_ACCESS_TIMEOUT_MS 200

/**
 * @brief EtherCAT plugin state machine states
 *
 * State transitions:
 *   STOPPED -> IDLE -> SCANNING -> CONFIGURING -> TRANSITIONING -> OPERATIONAL
 *   OPERATIONAL <-> RECOVERING
 *   RECOVERING -> ERROR (after max attempts)
 *   Any state -> STOPPED (via stop_loop)
 */
typedef enum {
    ECAT_STATE_IDLE,           /* After init(), before start_loop()         */
    ECAT_STATE_SCANNING,       /* ecx_init + ecx_config_init               */
    ECAT_STATE_CONFIGURING,    /* SDO writes + PDO mapping                 */
    ECAT_STATE_TRANSITIONING,  /* Slaves moving to SAFE-OP -> OP           */
    ECAT_STATE_OPERATIONAL,    /* Normal cyclic operation                   */
    ECAT_STATE_RECOVERING,     /* Attempting to recover slaves              */
    ECAT_STATE_ERROR,          /* Unrecoverable error                      */
    ECAT_STATE_STOPPED         /* After stop_loop() or before init()       */
} ecat_plugin_state_t;

/**
 * @brief Per-slave status snapshot for monitoring
 */
typedef struct {
    int      position;
    char     name[ECAT_MAX_NAME_LEN];
    uint16_t al_state;          /* EC_STATE_* from SOEM                    */
    uint16_t al_status_code;
    uint32_t error_count;
} ecat_slave_status_t;

/**
 * @brief Master-level status snapshot for monitoring and diagnostics
 *
 * Updated periodically by the PLC scan cycle under g_status_mutex.
 * Read by execute_command handlers for the "status" and "diagnostics" commands.
 */
typedef struct {
    ecat_plugin_state_t plugin_state;
    int                 slave_count;
    ecat_slave_status_t slaves[ECAT_MAX_SLAVES];
    uint64_t            cycle_count;
    uint64_t            wkc_error_count;
    uint64_t            avg_cycle_us;
    uint64_t            max_cycle_us;
    uint64_t            max_exchange_us;
    int                 consecutive_wkc_errors;
    int                 recovery_attempts;
    int                 expected_wkc;
    uint64_t            exchange_skips;
} ecat_master_status_t;

/**
 * @brief Convert plugin state enum to human-readable string
 *
 * @param state Plugin state value
 * @return Static string representation (e.g., "OPERATIONAL")
 */
const char *ecat_state_to_string(ecat_plugin_state_t state);

/**
 * @brief Get the size in bytes for a given EtherCAT data type
 *
 * Used for SDO write operations to determine the payload size.
 *
 * @param dt Data type enum value
 * @return Size in bytes (0 for UNKNOWN/PAD, 1 for BOOL)
 */
int ecat_data_type_size(ecat_data_type_t dt);

#endif /* ETHERCAT_CONFIG_H */
