/**
 * @file ethercat_plugin.h
 * @brief EtherCAT Plugin Interface for OpenPLC Runtime v4
 *
 * This plugin implements an EtherCAT master using the SOEM library.
 * It reads the EtherCAT configuration JSON generated by the OpenPLC Editor,
 * initializes the SOEM master, validates the bus topology against the
 * expected configuration, and manages process data exchange with slaves.
 *
 * Plugin lifecycle:
 *   init()        -> Load config, initialize logger
 *   start_loop()  -> Initialize SOEM master, validate topology
 *   cycle_start() -> Read inputs from slaves (Phase 2)
 *   cycle_end()   -> Write outputs to slaves (Phase 2)
 *   stop_loop()   -> Transition slaves to INIT, close master
 *   cleanup()     -> Free resources
 */

#ifndef ETHERCAT_PLUGIN_H
#define ETHERCAT_PLUGIN_H

/**
 * @brief Initialize the EtherCAT plugin
 *
 * Copies runtime args, initializes logger, loads and parses JSON config.
 *
 * @param args Pointer to plugin_runtime_args_t (freed after init returns)
 * @return 0 on success, -1 on failure
 */
int init(void *args);

/**
 * @brief Start the EtherCAT master
 *
 * Initializes SOEM, scans the bus, validates topology, and transitions
 * slaves to operational state.
 */
void start_loop(void);

/**
 * @brief Stop the EtherCAT master
 *
 * Transitions all slaves to INIT state and closes the network interface.
 */
void stop_loop(void);

/**
 * @brief Cleanup plugin resources
 */
void cleanup(void);

/**
 * @brief Called at the start of each PLC scan cycle
 *
 * Phase 1: Stub (no-op)
 * Phase 2: Will read process inputs from slaves
 */
void cycle_start(void);

/**
 * @brief Called at the end of each PLC scan cycle
 *
 * Phase 1: Stub (no-op)
 * Phase 2: Will write process outputs to slaves
 */
void cycle_end(void);

#endif /* ETHERCAT_PLUGIN_H */
