/**
 * @file ethercat_plugin.c
 * @brief EtherCAT Plugin Implementation for OpenPLC Runtime v4
 *
 * This plugin implements an EtherCAT master using the SOEM library.
 * It consumes the ethercat.json configuration generated by the OpenPLC Editor
 * and manages the EtherCAT bus lifecycle.
 *
 * Phase 1: Config parsing, SOEM init, topology validation
 * Phase 2: Process data exchange in cycle_start/cycle_end
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "plugin_logger.h"
#include "plugin_types.h"
#include "ethercat_plugin.h"
#include "ethercat_config.h"
#include "ethercat_master.h"
#include "ethercat_io.h"
#include "soem/soem.h"   /* osal_get_monotonic_time, ec_timet */
#include "cjson/cJSON.h"  /* JSON parsing for execute_command */

/*
 * =============================================================================
 * Cycle Diagnostics
 * =============================================================================
 */

/** Number of cycles between diagnostic log reports */
#define ECAT_DIAG_REPORT_INTERVAL 10000

typedef struct {
    uint64_t cycle_count;         /* total cycles executed              */
    uint64_t wkc_error_count;     /* total WKC errors (wkc < expected)  */
    uint64_t noframe_count;       /* total EC_NOFRAME (-1) errors       */
    uint64_t exchange_ns;         /* last send+receive duration (ns)    */
    uint64_t io_read_ns;          /* last read_inputs duration (ns)     */
    uint64_t io_write_ns;         /* last write_outputs duration (ns)   */
    uint64_t total_ns;            /* last full cycle total (ns)         */
    uint64_t max_exchange_ns;     /* worst-case send+receive            */
    uint64_t max_total_ns;        /* worst-case total                   */
    uint64_t sum_total_ns;        /* running sum for average            */
} ecat_cycle_diag_t;

/**
 * @brief Convert ec_timet (struct timespec) to nanoseconds
 */
static inline uint64_t timespec_to_ns(const ec_timet *ts)
{
    return (uint64_t)ts->tv_sec * 1000000000ULL + (uint64_t)ts->tv_nsec;
}

/**
 * @brief Return elapsed nanoseconds between two timestamps
 */
static inline uint64_t elapsed_ns(const ec_timet *start, const ec_timet *end)
{
    return timespec_to_ns(end) - timespec_to_ns(start);
}

/*
 * =============================================================================
 * Plugin State
 * =============================================================================
 */
static plugin_logger_t g_logger;
static plugin_runtime_args_t g_runtime_args;
static ecat_config_t g_config;
static bool g_initialized = false;
static bool g_running = false;
static ecat_channel_map_t g_channel_map;
static int g_consecutive_wkc_errors = 0;
static int g_expected_wkc = 0;
static int g_receive_timeout_us = 0;
static ecat_cycle_diag_t g_diag;

/*
 * =============================================================================
 * Plugin Lifecycle Functions
 * =============================================================================
 */

/**
 * @brief Initialize the EtherCAT plugin
 */
int init(void *args)
{
    /* Initialize logger first (before we have runtime_args) */
    plugin_logger_init(&g_logger, "ETHERCAT", NULL);
    plugin_logger_info(&g_logger, "Initializing EtherCAT plugin...");

    if (!args) {
        plugin_logger_error(&g_logger, "init args is NULL");
        return -1;
    }

    /* Copy runtime args (critical - pointer is freed after init returns) */
    memcpy(&g_runtime_args, args, sizeof(plugin_runtime_args_t));

    /* Re-initialize logger with runtime_args for central logging */
    plugin_logger_init(&g_logger, "ETHERCAT", args);

    plugin_logger_info(&g_logger, "Buffer size: %d", g_runtime_args.buffer_size);

    /* Parse configuration file */
    const char *config_path = g_runtime_args.plugin_specific_config_file_path;
    if (config_path == NULL || config_path[0] == '\0') {
        plugin_logger_warn(&g_logger, "No config file specified, using defaults");
        ecat_config_init_defaults(&g_config);
    } else {
        plugin_logger_info(&g_logger, "Loading config: %s", config_path);
        int result = ecat_config_parse(config_path, &g_config);
        if (result != ECAT_CONFIG_OK) {
            plugin_logger_error(&g_logger, "Failed to parse config file (error %d)", result);
            plugin_logger_warn(&g_logger, "Using default configuration");
            ecat_config_init_defaults(&g_config);
        } else {
            plugin_logger_info(&g_logger, "Configuration loaded successfully");
        }
    }

    /* Log configuration summary */
    plugin_logger_info(&g_logger, "Master config: interface=%s, cycle_time=%d us, watchdog=%d cycles",
                       g_config.master.interface,
                       g_config.master.cycle_time_us,
                       g_config.master.watchdog_timeout_cycles);
    plugin_logger_info(&g_logger, "Slaves configured: %d", g_config.slave_count);

    for (int i = 0; i < g_config.slave_count; i++) {
        const ecat_slave_t *slave = &g_config.slaves[i];
        plugin_logger_info(&g_logger, "  Slave %d: %s (%s) vendor=0x%08X product=0x%08X channels=%d",
                           slave->position, slave->name, slave->type,
                           slave->vendor_id, slave->product_code,
                           slave->channel_count);
    }

    g_initialized = true;
    plugin_logger_info(&g_logger, "EtherCAT plugin initialized successfully");

    return 0;
}

/**
 * @brief Start the EtherCAT master
 */
void start_loop(void)
{
    if (!g_initialized) {
        plugin_logger_error(&g_logger, "Cannot start - plugin not initialized");
        return;
    }

    if (g_running) {
        plugin_logger_warn(&g_logger, "EtherCAT master already running");
        return;
    }

    if (g_config.slave_count == 0) {
        plugin_logger_warn(&g_logger, "No slaves configured - EtherCAT master will not start");
        return;
    }

    plugin_logger_info(&g_logger, "Starting EtherCAT master on interface %s...",
                       g_config.master.interface);

    int result = ecat_master_init(&g_config, &g_logger);
    if (result != 0) {
        plugin_logger_error(&g_logger, "Failed to initialize EtherCAT master (error %d)", result);
        return;
    }

    /* Build channel map for process data exchange */
    ecat_io_build_channel_map(&g_config, &g_channel_map, &g_runtime_args, &g_logger);

    /* Cache expected WKC — it never changes after config_map_group */
    g_expected_wkc = ecat_master_get_expected_wkc();
    plugin_logger_info(&g_logger, "Expected WKC: %d", g_expected_wkc);

    g_receive_timeout_us = g_config.master.receive_timeout_us;
    plugin_logger_info(&g_logger, "Receive timeout: %d us", g_receive_timeout_us);

    /* Reset cycle state */
    g_consecutive_wkc_errors = 0;
    memset(&g_diag, 0, sizeof(g_diag));

    g_running = true;
    plugin_logger_info(&g_logger, "EtherCAT master started successfully");
}

/**
 * @brief Stop the EtherCAT master
 */
void stop_loop(void)
{
    if (!g_running) {
        plugin_logger_debug(&g_logger, "EtherCAT master already stopped");
        return;
    }

    plugin_logger_info(&g_logger, "Stopping EtherCAT master...");

    /* Log final diagnostics */
    if (g_diag.cycle_count > 0 || g_diag.wkc_error_count > 0) {
        uint64_t total_cycles = g_diag.cycle_count + g_diag.wkc_error_count;
        uint64_t avg_us = g_diag.cycle_count > 0
            ? (g_diag.sum_total_ns / g_diag.cycle_count) / 1000 : 0;
        plugin_logger_info(&g_logger,
            "Final cycle stats: %llu total (%llu ok, %llu errors), "
            "avg=%llu us, max_total=%llu us, max_exchange=%llu us",
            (unsigned long long)total_cycles,
            (unsigned long long)g_diag.cycle_count,
            (unsigned long long)g_diag.wkc_error_count,
            (unsigned long long)avg_us,
            (unsigned long long)(g_diag.max_total_ns / 1000),
            (unsigned long long)(g_diag.max_exchange_ns / 1000));
        if (g_diag.wkc_error_count > 0) {
            plugin_logger_info(&g_logger,
                "WKC error summary: %llu noframe (-1), error rate=%.1f%%",
                (unsigned long long)g_diag.noframe_count,
                total_cycles > 0 ? (g_diag.wkc_error_count * 100.0 / total_cycles) : 0.0);
        }
    }

    memset(&g_channel_map, 0, sizeof(g_channel_map));
    g_consecutive_wkc_errors = 0;
    g_expected_wkc = 0;

    ecat_master_close(&g_logger);
    g_running = false;

    plugin_logger_info(&g_logger, "EtherCAT master stopped");
}

/**
 * @brief Cleanup plugin resources
 */
void cleanup(void)
{
    plugin_logger_info(&g_logger, "Cleaning up EtherCAT plugin...");

    if (g_running) {
        stop_loop();
    }

    g_initialized = false;
    plugin_logger_info(&g_logger, "EtherCAT plugin cleanup complete");
}

/**
 * @brief Called at the start of each PLC scan cycle
 *
 * Exchanges process data with the bus (sends previous outputs, receives
 * current inputs), then copies IOmap input data into PLC input buffers.
 * Measures exchange and I/O copy durations for diagnostics.
 */
void cycle_start(void)
{
    if (!g_running)
        return;

    ec_timet t0, t1, t2;

    /* Measure process data exchange */
    osal_get_monotonic_time(&t0);
    int wkc = ecat_master_exchange_processdata(g_receive_timeout_us);
    osal_get_monotonic_time(&t1);

    g_diag.exchange_ns = elapsed_ns(&t0, &t1);

    if (wkc < g_expected_wkc) {
        g_consecutive_wkc_errors++;
        g_diag.wkc_error_count++;
        if (wkc == EC_NOFRAME)
            g_diag.noframe_count++;

        if (g_consecutive_wkc_errors == 1 || (g_consecutive_wkc_errors % 100) == 0) {
            plugin_logger_warn(&g_logger,
                "WKC error: expected %d, got %d (consecutive: %d, "
                "exchange=%llu us, timeout=%d us)",
                g_expected_wkc, wkc, g_consecutive_wkc_errors,
                (unsigned long long)(g_diag.exchange_ns / 1000),
                g_receive_timeout_us);

            /* Log slave states on first error of each burst */
            if (g_consecutive_wkc_errors == 1) {
                for (int i = 0; i < g_config.slave_count; i++) {
                    const ec_slavet *slave =
                        ecat_master_get_slave(g_config.slaves[i].position);
                    if (slave) {
                        plugin_logger_warn(&g_logger,
                            "  Slave %d (%s): state=0x%04X, ALstatus=0x%04X",
                            g_config.slaves[i].position,
                            g_config.slaves[i].name,
                            slave->state, slave->ALstatuscode);
                    }
                }
            }
        }

        if (g_config.master.watchdog_timeout_cycles > 0 &&
            g_consecutive_wkc_errors >= g_config.master.watchdog_timeout_cycles) {
            if (g_consecutive_wkc_errors == g_config.master.watchdog_timeout_cycles) {
                plugin_logger_error(&g_logger,
                    "Watchdog triggered: %d consecutive WKC errors exceed threshold %d",
                    g_consecutive_wkc_errors, g_config.master.watchdog_timeout_cycles);
            }
        }
        return;
    }

    g_consecutive_wkc_errors = 0;

    /* Measure input copy */
    ecat_io_read_inputs(&g_channel_map, &g_runtime_args);
    osal_get_monotonic_time(&t2);

    g_diag.io_read_ns = elapsed_ns(&t1, &t2);
}

/**
 * @brief Called at the end of each PLC scan cycle
 *
 * Copies PLC output buffers into the IOmap so they are sent on the
 * next cycle_start() process data exchange.
 * Accumulates cycle diagnostics and logs periodic reports.
 */
void cycle_end(void)
{
    if (!g_running)
        return;

    /* Skip output update if watchdog has been triggered */
    if (g_config.master.watchdog_timeout_cycles > 0 &&
        g_consecutive_wkc_errors >= g_config.master.watchdog_timeout_cycles) {
        return;
    }

    ec_timet t0, t1;

    /* Measure output copy */
    osal_get_monotonic_time(&t0);
    ecat_io_write_outputs(&g_channel_map, &g_runtime_args);
    osal_get_monotonic_time(&t1);

    g_diag.io_write_ns = elapsed_ns(&t0, &t1);

    /* Update diagnostics */
    g_diag.total_ns = g_diag.exchange_ns + g_diag.io_read_ns + g_diag.io_write_ns;
    g_diag.cycle_count++;
    g_diag.sum_total_ns += g_diag.total_ns;

    if (g_diag.exchange_ns > g_diag.max_exchange_ns)
        g_diag.max_exchange_ns = g_diag.exchange_ns;
    if (g_diag.total_ns > g_diag.max_total_ns)
        g_diag.max_total_ns = g_diag.total_ns;

    /* Periodic diagnostics report */
    if ((g_diag.cycle_count % ECAT_DIAG_REPORT_INTERVAL) == 0) {
        uint64_t total_cycles = g_diag.cycle_count + g_diag.wkc_error_count;
        uint64_t avg_us = (g_diag.sum_total_ns / g_diag.cycle_count) / 1000;
        plugin_logger_info(&g_logger,
            "Cycle stats (%llu total): avg=%llu us, max_total=%llu us, "
            "max_exchange=%llu us, last=[exch=%llu us, rd=%llu us, wr=%llu us]",
            (unsigned long long)total_cycles,
            (unsigned long long)avg_us,
            (unsigned long long)(g_diag.max_total_ns / 1000),
            (unsigned long long)(g_diag.max_exchange_ns / 1000),
            (unsigned long long)(g_diag.exchange_ns / 1000),
            (unsigned long long)(g_diag.io_read_ns / 1000),
            (unsigned long long)(g_diag.io_write_ns / 1000));
        plugin_logger_info(&g_logger,
            "WKC errors: %llu total, %llu noframe (-1), error rate=%.1f%%",
            (unsigned long long)g_diag.wkc_error_count,
            (unsigned long long)g_diag.noframe_count,
            total_cycles > 0 ? (g_diag.wkc_error_count * 100.0 / total_cycles) : 0.0);
    }
}

/*
 * =============================================================================
 * Async Command Handling (execute_command)
 * =============================================================================
 */

/**
 * @brief Handle the "scan" command using a temporary SOEM context
 *
 * Creates a separate ecx_contextt (not the master's g_ecx_context) to scan
 * the bus for slaves. This allows scanning even when the master is not running.
 */
static int handle_scan_command(cJSON *root, char *response, size_t response_size)
{
    cJSON *params = cJSON_GetObjectItemCaseSensitive(root, "params");
    cJSON *iface = params ? cJSON_GetObjectItemCaseSensitive(params, "interface") : NULL;

    if (!iface || !cJSON_IsString(iface)) {
        snprintf(response, response_size, "{\"error\":\"missing 'interface' param\"}");
        return -1;
    }

    /* Refuse scan while master is actively running on the bus */
    if (g_running) {
        snprintf(response, response_size,
            "{\"error\":\"EtherCAT master is running. Stop the PLC before scanning.\"}");
        return -1;
    }

    /* Temporary SOEM context for scan (independent from the master context) */
    ecx_contextt scan_ctx;
    memset(&scan_ctx, 0, sizeof(scan_ctx));

    if (!ecx_init(&scan_ctx, iface->valuestring)) {
        snprintf(response, response_size,
            "{\"error\":\"Failed to open interface '%s'\"}", iface->valuestring);
        return -1;
    }

    int slave_count = ecx_config_init(&scan_ctx);
    if (slave_count <= 0) {
        ecx_close(&scan_ctx);
        snprintf(response, response_size,
            "{\"status\":\"success\",\"devices\":[],\"message\":\"No slaves found\",\"slave_count\":0}");
        return 0;
    }

    /* Build JSON response with discovered slaves */
    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON *devices = cJSON_AddArrayToObject(resp, "devices");

    for (int i = 1; i <= scan_ctx.slavecount; i++) {
        ec_slavet *s = &scan_ctx.slavelist[i];
        cJSON *dev = cJSON_CreateObject();
        cJSON_AddNumberToObject(dev, "position", i);
        cJSON_AddStringToObject(dev, "name", s->name);
        cJSON_AddNumberToObject(dev, "vendor_id", s->eep_man);
        cJSON_AddNumberToObject(dev, "product_code", s->eep_id);
        cJSON_AddNumberToObject(dev, "revision", s->eep_rev);
        cJSON_AddNumberToObject(dev, "serial_number", s->eep_ser);
        cJSON_AddStringToObject(dev, "state", "UNKNOWN");
        cJSON_AddNumberToObject(dev, "al_status_code", 0);
        cJSON_AddBoolToObject(dev, "has_coe", (s->mbx_proto & 0x04) != 0);
        cJSON_AddNumberToObject(dev, "input_bytes", 0);
        cJSON_AddNumberToObject(dev, "output_bytes", 0);
        cJSON_AddItemToArray(devices, dev);
    }

    char msg[128];
    snprintf(msg, sizeof(msg), "Found %d EtherCAT slave(s)", scan_ctx.slavecount);
    cJSON_AddStringToObject(resp, "message", msg);
    cJSON_AddNumberToObject(resp, "slave_count", scan_ctx.slavecount);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    ecx_close(&scan_ctx);
    return 0;
}

/**
 * @brief Execute an async command routed from the unix socket
 */
int execute_command(const char *command_json, char *response, size_t response_size)
{
    cJSON *root = cJSON_Parse(command_json);
    if (!root) {
        snprintf(response, response_size, "{\"error\":\"invalid JSON\"}");
        return -1;
    }

    cJSON *cmd = cJSON_GetObjectItemCaseSensitive(root, "command");
    if (!cmd || !cJSON_IsString(cmd)) {
        cJSON_Delete(root);
        snprintf(response, response_size, "{\"error\":\"missing 'command' field\"}");
        return -1;
    }

    int result = -1;
    if (strcmp(cmd->valuestring, "scan") == 0) {
        result = handle_scan_command(root, response, response_size);
    } else {
        snprintf(response, response_size, "{\"error\":\"unknown command '%s'\"}", cmd->valuestring);
    }

    cJSON_Delete(root);
    return result;
}
