/**
 * @file ethercat_config.h
 * @brief EtherCAT Plugin Configuration Structures and Parser Interface
 *
 * Defines the C structures that mirror the JSON configuration contract
 * generated by the OpenPLC Editor. The JSON is parsed using cJSON and
 * mapped into these structures for use by the EtherCAT master.
 */

#ifndef ETHERCAT_CONFIG_H
#define ETHERCAT_CONFIG_H

#include <stdbool.h>
#include <stdint.h>

/* Maximum sizes */
#define ECAT_MAX_SLAVES      64
#define ECAT_MAX_CHANNELS    64
#define ECAT_MAX_PDO_ENTRIES 32
#define ECAT_MAX_PDOS        16
#define ECAT_MAX_SDOS        32
#define ECAT_MAX_NAME_LEN    64
#define ECAT_MAX_IEC_LOC_LEN 16

/* Error codes */
#define ECAT_CONFIG_OK              0
#define ECAT_CONFIG_ERR_FILE       -1
#define ECAT_CONFIG_ERR_PARSE      -2
#define ECAT_CONFIG_ERR_MEMORY     -3
#define ECAT_CONFIG_ERR_INVALID    -4
#define ECAT_CONFIG_ERR_MISSING    -5

/**
 * @brief PDO entry definition
 *
 * Represents a single entry within a PDO (Process Data Object).
 * Entries with index "0x0000" are padding entries.
 */
typedef struct {
    char     index[12];        /* hex string e.g. "0x6000" */
    uint8_t  subindex;
    uint8_t  bit_length;
    char     name[ECAT_MAX_NAME_LEN];
    char     data_type[12];    /* "BOOL", "INT16", "PAD", etc. */
} ecat_pdo_entry_t;

/**
 * @brief PDO (Process Data Object) definition
 *
 * Contains the PDO index and its list of entries.
 * RxPDOs are written to the slave, TxPDOs are read from the slave.
 */
typedef struct {
    char             index[12];  /* hex string e.g. "0x1A00" */
    char             name[ECAT_MAX_NAME_LEN];
    ecat_pdo_entry_t entries[ECAT_MAX_PDO_ENTRIES];
    int              entry_count;
} ecat_pdo_t;

/**
 * @brief SDO configuration entry
 *
 * Defines an SDO (Service Data Object) parameter to be written
 * to a slave during configuration phase.
 */
typedef struct {
    char     index[12];        /* hex string e.g. "0x8000" */
    uint8_t  subindex;
    int32_t  value;
    char     data_type[12];
    char     name[ECAT_MAX_NAME_LEN];
} ecat_sdo_config_t;

/**
 * @brief Channel mapping definition
 *
 * Maps a physical I/O channel to an IEC 61131-3 located variable.
 * Links the channel to its corresponding PDO entry.
 */
typedef struct {
    int      index;
    char     name[ECAT_MAX_NAME_LEN];
    char     type[20];         /* "digital_input", "analog_output", etc. */
    uint8_t  bit_length;
    char     iec_location[ECAT_MAX_IEC_LOC_LEN];
    char     pdo_index[12];
    char     pdo_entry_index[12];
    uint8_t  pdo_entry_subindex;
} ecat_channel_t;

/**
 * @brief EtherCAT slave configuration
 *
 * Complete configuration for a single EtherCAT slave device,
 * including identity, channel mappings, PDOs, and SDOs.
 */
typedef struct {
    int               position;        /* ec_slave[position] in SOEM (1-based) */
    char              name[ECAT_MAX_NAME_LEN];
    char              type[20];        /* "coupler", "digital_input", etc. */
    uint32_t          vendor_id;
    uint32_t          product_code;
    uint32_t          revision;
    ecat_channel_t    channels[ECAT_MAX_CHANNELS];
    int               channel_count;
    ecat_sdo_config_t sdo_configs[ECAT_MAX_SDOS];
    int               sdo_count;
    ecat_pdo_t        rx_pdos[ECAT_MAX_PDOS];
    int               rx_pdo_count;
    ecat_pdo_t        tx_pdos[ECAT_MAX_PDOS];
    int               tx_pdo_count;
} ecat_slave_t;

/**
 * @brief Master configuration parameters
 */
typedef struct {
    char             interface[32];
    int              cycle_time_us;
    int              watchdog_timeout_cycles;
    char             log_level[8];
} ecat_master_config_t;

/**
 * @brief Diagnostics configuration
 */
typedef struct {
    bool             log_connections;
    bool             log_data_access;
    bool             log_errors;
    int              max_log_entries;
    int              status_update_interval_ms;
} ecat_diagnostics_config_t;

/**
 * @brief Top-level EtherCAT configuration
 *
 * Contains the master settings, flat list of slaves, and diagnostics config.
 *
 * WARNING: This struct is approximately 7 MB due to the inline slave array
 * with nested PDOs. It must be allocated statically or on the heap -- never
 * on the stack, as it would overflow most thread stacks.
 */
typedef struct {
    ecat_master_config_t      master;
    ecat_slave_t              slaves[ECAT_MAX_SLAVES];
    int                       slave_count;
    ecat_diagnostics_config_t diagnostics;
} ecat_config_t;

/**
 * @brief Parse EtherCAT configuration from a JSON file
 *
 * Reads and parses the JSON configuration file generated by the OpenPLC Editor.
 * The JSON has an array root format: [{ name, protocol, config }].
 * The "config" object is extracted and mapped to the ecat_config_t structure.
 *
 * @param config_path Path to the JSON configuration file
 * @param config Output configuration structure
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_parse(const char *config_path, ecat_config_t *config);

/**
 * @brief Validate a parsed configuration
 *
 * Checks required fields, value ranges, and IEC location format.
 *
 * @param config Configuration to validate
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_validate(const ecat_config_t *config);

/**
 * @brief Initialize configuration with default values
 *
 * @param config Configuration structure to initialize
 */
void ecat_config_init_defaults(ecat_config_t *config);

#endif /* ETHERCAT_CONFIG_H */
