/**
 * @file ethercat_plugin.h
 * @brief EtherCAT Plugin Interface for OpenPLC Runtime v4
 *
 * This plugin implements an EtherCAT master using the SOEM library.
 * It reads the EtherCAT configuration JSON generated by the OpenPLC Editor,
 * initializes the SOEM master, validates the bus topology against the
 * expected configuration, and manages process data exchange with slaves.
 *
 * Plugin lifecycle:
 *   init()        -> Load config, initialize logger [state: IDLE]
 *   start_loop()  -> Scan bus, write SDOs, map PDOs, transition to OP,
 *                    start independent EtherCAT cycle thread [state: OPERATIONAL]
 *   cycle_start() -> Copy shadow buffer inputs to PLC buffers
 *   cycle_end()   -> Copy PLC buffers to shadow buffer outputs
 *   stop_loop()   -> Join cycle thread, close master [state: STOPPED]
 *   cleanup()     -> Free resources
 *
 * State machine: STOPPED -> IDLE -> SCANNING -> CONFIGURING ->
 *                TRANSITIONING -> OPERATIONAL <-> RECOVERING -> ERROR
 *
 * Commands: "scan", "status", "diagnostics"
 */

#ifndef ETHERCAT_PLUGIN_H
#define ETHERCAT_PLUGIN_H

/**
 * @brief Initialize the EtherCAT plugin
 *
 * Copies runtime args, initializes logger, loads and parses JSON config.
 *
 * @param args Pointer to plugin_runtime_args_t (freed after init returns)
 * @return 0 on success, -1 on failure
 */
int init(void *args);

/**
 * @brief Start the EtherCAT master
 *
 * Initializes SOEM, scans the bus, validates topology, and transitions
 * slaves to operational state.
 */
void start_loop(void);

/**
 * @brief Stop the EtherCAT master
 *
 * Transitions all slaves to INIT state and closes the network interface.
 */
void stop_loop(void);

/**
 * @brief Cleanup plugin resources
 */
void cleanup(void);

/**
 * @brief Called at the start of each PLC scan cycle
 *
 * Copies input data from the shadow IOmap into PLC input buffers.
 * The actual bus exchange happens in the independent EtherCAT cycle thread.
 */
void cycle_start(void);

/**
 * @brief Called at the end of each PLC scan cycle
 *
 * Copies PLC output buffers into the shadow IOmap.
 * The actual bus exchange happens in the independent EtherCAT cycle thread.
 */
void cycle_end(void);

/**
 * @brief Execute an async command
 *
 * Supported commands:
 *   - "scan": Scan bus for slaves (uses temporary SOEM context)
 *   - "status": Return current master/slave status snapshot
 *   - "diagnostics": Return detailed timing and recovery diagnostics
 *
 * @param command_json JSON string with "command" and optional "params" fields
 * @param response Buffer for JSON response
 * @param response_size Size of response buffer
 * @return 0 on success, -1 on error
 */
int execute_command(const char *command_json, char *response, size_t response_size);

#endif /* ETHERCAT_PLUGIN_H */
