/**
 * @file ethercat_plugin.c
 * @brief EtherCAT Plugin Implementation for OpenPLC Runtime v4
 *
 * This plugin implements an EtherCAT master using the SOEM library.
 * It consumes the ethercat.json configuration generated by the OpenPLC Editor
 * and manages the EtherCAT bus lifecycle with an explicit state machine.
 *
 * Phase 1: Config parsing, SOEM init, topology validation
 * Phase 2: SDO writes, PDO mapping, state transition to OPERATIONAL
 * Phase 3: Synchronous process data exchange within PLC scan cycle
 *
 * Architecture:
 *   - Process data exchange runs synchronously inside the PLC scan cycle
 *     via cycle_start/cycle_end hooks, sharing the PLC thread's timing.
 *   - cycle_start: writes outputs, exchanges process data, reads inputs
 *   - cycle_end: (no-op, outputs are sent at the start of the next cycle)
 *   - No separate EtherCAT thread or shadow buffer is needed.
 */

#include <ctype.h>
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <pthread.h>
#include <time.h>

#include "plugin_logger.h"
#include "plugin_types.h"
#include "ethercat_plugin.h"
#include "ethercat_config.h"
#include "ethercat_master.h"
#include "ethercat_io.h"
#include "soem/soem.h"   /* osal_get_monotonic_time, ec_timet */
#include "cjson/cJSON.h"  /* JSON parsing for execute_command */

/*
 * =============================================================================
 * Constants
 * =============================================================================
 */

/** Number of cycles between diagnostic log reports */
#define ECAT_DIAG_REPORT_INTERVAL 10000

/** Minimum timeout for receive in microseconds */
#define ECAT_MIN_RECEIVE_TIMEOUT_US 200

/*
 * =============================================================================
 * Cycle Diagnostics
 * =============================================================================
 */

typedef struct {
    uint64_t cycle_count;         /* total cycles executed              */
    uint64_t wkc_error_count;     /* total WKC errors (wkc < expected)  */
    uint64_t noframe_count;       /* total EC_NOFRAME (-1) errors       */
    uint64_t exchange_ns;         /* last send+receive duration (ns)    */
    uint64_t io_read_ns;          /* last read_inputs duration (ns)     */
    uint64_t io_write_ns;         /* last write_outputs duration (ns)   */
    uint64_t total_ns;            /* last full cycle total (ns)         */
    uint64_t max_exchange_ns;     /* worst-case send+receive            */
    uint64_t max_total_ns;        /* worst-case total                   */
    uint64_t sum_total_ns;        /* running sum for average            */
} ecat_cycle_diag_t;

/**
 * @brief Convert ec_timet (struct timespec) to nanoseconds
 */
static inline uint64_t timespec_to_ns(const ec_timet *ts)
{
    return (uint64_t)ts->tv_sec * 1000000000ULL + (uint64_t)ts->tv_nsec;
}

/**
 * @brief Return elapsed nanoseconds between two timestamps
 */
static inline uint64_t elapsed_ns(const ec_timet *start, const ec_timet *end)
{
    uint64_t s = timespec_to_ns(start);
    uint64_t e = timespec_to_ns(end);
    return (e > s) ? (e - s) : 0;
}

/*
 * =============================================================================
 * EtherCAT AL State to String Helper
 * =============================================================================
 */

/**
 * @brief Convert SOEM EC_STATE_* value to a human-readable string
 */
static const char *al_state_to_string(uint16_t state)
{
    /* Mask off the error bit for comparison */
    uint16_t base = state & 0x0F;
    int has_error = (state & EC_STATE_ERROR) != 0;

    const char *name;
    switch (base) {
    case EC_STATE_NONE:     name = "NONE";     break;
    case EC_STATE_INIT:     name = "INIT";     break;
    case EC_STATE_PRE_OP:   name = "PRE-OP";   break;
    case EC_STATE_BOOT:     name = "BOOT";     break;
    case EC_STATE_SAFE_OP:  name = "SAFE-OP";  break;
    case EC_STATE_OPERATIONAL: name = "OP";     break;
    default:                name = "UNKNOWN";  break;
    }

    /* Return static strings for common cases */
    if (!has_error)
        return name;

    /* For error states, we just note it. Since we return static strings,
     * use a small set of pre-defined error state strings. */
    switch (base) {
    case EC_STATE_INIT:    return "INIT+ERR";
    case EC_STATE_PRE_OP:  return "PRE-OP+ERR";
    case EC_STATE_SAFE_OP: return "SAFE-OP+ERR";
    default:               return "UNKNOWN+ERR";
    }
}

/*
 * =============================================================================
 * Plugin State
 * =============================================================================
 */

static plugin_logger_t g_logger;
static plugin_runtime_args_t g_runtime_args;
static ecat_config_t g_config;
static ecat_channel_map_t g_channel_map;
static ecat_transfer_list_t g_transfer_list;
static int g_expected_wkc = 0;
static int g_receive_timeout_us = 0;

/* State machine */
static _Atomic(int) g_plugin_state = ECAT_STATE_STOPPED;

/* Status snapshot for queries via execute_command.
 * Written in cycle_start() (PLC thread), read by execute_command (web thread). */
static ecat_master_status_t g_status_snapshot;
static pthread_mutex_t g_status_mutex = PTHREAD_MUTEX_INITIALIZER;

/* Diagnostics (updated by cycle_start in the PLC thread) */
static ecat_cycle_diag_t g_diag;
static _Atomic(int) g_consecutive_wkc_errors = 0;
static _Atomic(int) g_recovery_attempts = 0;
static uint64_t g_cycle_counter = 0;

#if ECAT_ENABLE_MONITOR_THREAD
/*
 * =============================================================================
 * Cooperative SOEM Access Protocol
 * =============================================================================
 *
 * SOEM is NOT thread-safe. The PLC thread and monitor thread must never call
 * SOEM functions concurrently. Instead of a mutex (which would cause priority
 * inversion), we use atomic flags for cooperative coordination:
 *
 *   Normal:  PLC exchanges data every cycle, monitor sleeps.
 *   Pause:   Monitor sets pause_requested. PLC sees flag, skips exchange,
 *            sets paused=true. Monitor does its SOEM work, then clears both.
 *   Resume:  PLC resumes exchange on the next cycle.
 *
 * Worst-case PLC impact: 1 cycle with stale I/O data per monitor interval.
 */
static pthread_t g_monitor_thread;
static _Atomic(bool) g_monitor_running = false;
static _Atomic(bool) g_soem_pause_requested = false;
static _Atomic(bool) g_soem_paused = false;
static _Atomic(uint64_t) g_exchange_skips = 0;
#endif /* ECAT_ENABLE_MONITOR_THREAD */

/*
 * =============================================================================
 * Status Snapshot Update
 * =============================================================================
 */

/**
 * @brief Build and publish a status snapshot from current state
 *
 * Called by the monitor thread (or from start_loop/stop_loop).
 * The lock hold time is just a memcpy of ~5KB.
 */
static void update_status_snapshot(void)
{
    ecat_master_status_t snap;
    memset(&snap, 0, sizeof(snap));

    snap.plugin_state = (ecat_plugin_state_t)atomic_load(&g_plugin_state);
    snap.slave_count = g_config.slave_count;
    snap.expected_wkc = g_expected_wkc;
    snap.consecutive_wkc_errors = g_consecutive_wkc_errors;
    snap.recovery_attempts = g_recovery_attempts;
#if ECAT_ENABLE_MONITOR_THREAD
    snap.exchange_skips = atomic_load(&g_exchange_skips);
#endif

    /* Cycle metrics */
    snap.cycle_count = g_diag.cycle_count;
    snap.wkc_error_count = g_diag.wkc_error_count;
    snap.max_cycle_us = g_diag.max_total_ns / 1000;
    snap.max_exchange_us = g_diag.max_exchange_ns / 1000;
    snap.avg_cycle_us = g_diag.cycle_count > 0
        ? (g_diag.sum_total_ns / g_diag.cycle_count) / 1000 : 0;

    /* Per-slave status */
    for (int i = 0; i < g_config.slave_count && i < ECAT_MAX_SLAVES; i++) {
        const ecat_slave_t *cfg = &g_config.slaves[i];
        ecat_slave_status_t *ss = &snap.slaves[i];

        ss->position = cfg->position;
        strncpy(ss->name, cfg->name, ECAT_MAX_NAME_LEN - 1);
        ss->name[ECAT_MAX_NAME_LEN - 1] = '\0';

        const ec_slavet *soem = ecat_master_get_slave(cfg->position);
        if (soem) {
            ss->al_state = soem->state;
            ss->al_status_code = soem->ALstatuscode;
        }
    }

    pthread_mutex_lock(&g_status_mutex);
    memcpy(&g_status_snapshot, &snap, sizeof(snap));
    pthread_mutex_unlock(&g_status_mutex);
}

#if ECAT_ENABLE_MONITOR_THREAD
/*
 * =============================================================================
 * Recovery Logic (runs in monitor thread, never in PLC scan cycle)
 * =============================================================================
 */

/**
 * @brief Attempt to recover all slaves that are not in OP
 *
 * MUST be called only when the PLC thread has yielded SOEM access
 * (g_soem_paused == true), because these SOEM calls are blocking and
 * not thread-safe.
 *
 * @return 1 if all slaves back in OP, 0 if some still recovering, -1 on max attempts
 */
static int attempt_recovery(void)
{
    ecat_master_read_states();

    int all_ok = 1;

    for (int i = 0; i < g_config.slave_count; i++) {
        int pos = g_config.slaves[i].position;
        uint16_t state = ecat_master_get_slave_state(pos);

        if (state != EC_STATE_OPERATIONAL) {
            all_ok = 0;
            int result = ecat_master_recover_slave(pos, &g_logger);
            if (result < 0) {
                plugin_logger_error(&g_logger,
                    "Slave %d (%s): recovery error",
                    pos, g_config.slaves[i].name);
            }
        }
    }

    if (all_ok) {
        plugin_logger_info(&g_logger,
            "All slaves recovered to OPERATIONAL (attempts=%d)",
            g_recovery_attempts);
        g_recovery_attempts = 0;
        g_consecutive_wkc_errors = 0;
        return 1;
    }

    g_recovery_attempts++;

    if (g_recovery_attempts >= ECAT_MAX_RECOVERY_ATTEMPTS) {
        plugin_logger_error(&g_logger,
            "Maximum recovery attempts (%d) reached - transitioning to ERROR",
            ECAT_MAX_RECOVERY_ATTEMPTS);
        return -1;
    }

    plugin_logger_warn(&g_logger, "Recovery attempt %d/%d - some slaves not yet in OP",
                       g_recovery_attempts, ECAT_MAX_RECOVERY_ATTEMPTS);
    return 0;
}

/*
 * =============================================================================
 * Cooperative SOEM Access Helpers
 * =============================================================================
 */

/**
 * @brief Request exclusive SOEM access from the PLC thread
 *
 * Sets the pause request flag and waits for the PLC thread to acknowledge.
 * The PLC thread checks this flag at the top of cycle_start() and, when set,
 * skips the SOEM exchange and signals g_soem_paused.
 *
 * The paused flag is cleared before requesting to prevent a stale
 * acknowledgment from a previous release/request window from being
 * misinterpreted as a fresh yield. Without this, the following race
 * can occur:
 *
 *   1. release_soem_access() stores pause_requested=false
 *   2. PLC cycle_start() sees the (not-yet-cleared) pause_requested=true,
 *      sets paused=true, and skips the exchange
 *   3. release_soem_access() stores paused=false -- but step 2 already
 *      overwrote it back to true
 *   4. On the next monitor interval, request_soem_access() sees the
 *      stale paused=true and returns immediately, even though the PLC
 *      thread is actively using SOEM
 *
 * Clearing paused first ensures we only succeed when the PLC thread
 * acknowledges *this* specific request.
 *
 * @param timeout_ms Maximum time to wait for PLC thread acknowledgment
 * @return true if SOEM access was granted, false on timeout
 */
static bool request_soem_access(int timeout_ms)
{
    /* Clear any stale acknowledgment before raising a new request */
    atomic_store(&g_soem_paused, false);
    atomic_store(&g_soem_pause_requested, true);

    struct timespec ts = { 0, 1000000 }; /* 1 ms poll interval */
    int waited_ms = 0;
    while (!atomic_load(&g_soem_paused) && waited_ms < timeout_ms) {
        nanosleep(&ts, NULL);
        waited_ms++;
    }

    if (!atomic_load(&g_soem_paused)) {
        atomic_store(&g_soem_pause_requested, false);
        return false;
    }
    return true;
}

/**
 * @brief Release exclusive SOEM access, allowing PLC thread to resume exchange
 *
 * The request flag is cleared first so that the PLC thread stops yielding
 * before the acknowledgment flag is reset.  This prevents a PLC cycle
 * that lands between the two stores from re-setting paused=true (which
 * would leave a stale acknowledgment for the next request_soem_access).
 */
static void release_soem_access(void)
{
    atomic_store(&g_soem_pause_requested, false);
    atomic_store(&g_soem_paused, false);
}

/*
 * =============================================================================
 * Background Monitor Thread
 * =============================================================================
 */

/**
 * @brief Background thread for slave state monitoring and recovery
 *
 * Runs at default (non-RT) priority. Periodically:
 *   - Requests exclusive SOEM access (PLC skips 1 exchange cycle)
 *   - Reads slave states via ecx_readstate()
 *   - Performs recovery if in RECOVERING state
 *   - Updates status snapshot for execute_command queries
 *   - Logs periodic diagnostics
 *
 * This keeps all blocking SOEM state/recovery calls OUT of the PLC scan cycle.
 */
static void *ecat_monitor_thread(void *arg)
{
    (void)arg;

    plugin_logger_info(&g_logger,
        "EtherCAT monitor thread started (interval=%d ms)",
        ECAT_MONITOR_INTERVAL_MS);

    while (atomic_load(&g_monitor_running)) {
        int state = atomic_load(&g_plugin_state);

        if (state == ECAT_STATE_OPERATIONAL) {
            /* Periodic state check */
            if (request_soem_access(ECAT_SOEM_ACCESS_TIMEOUT_MS)) {
                ecat_master_read_states();
                release_soem_access();
                update_status_snapshot();
            }

        } else if (state == ECAT_STATE_RECOVERING) {
            /* Recovery needs extended SOEM access */
            if (request_soem_access(ECAT_SOEM_ACCESS_TIMEOUT_MS)) {
                int result = attempt_recovery();
                release_soem_access();

                if (result == 1) {
                    atomic_store(&g_plugin_state, ECAT_STATE_OPERATIONAL);
                    plugin_logger_info(&g_logger,
                        "[state: OPERATIONAL] Recovered from error");
                } else if (result == -1) {
                    atomic_store(&g_plugin_state, ECAT_STATE_ERROR);
                    plugin_logger_error(&g_logger,
                        "EtherCAT entered ERROR state after max recovery attempts");
                }
                update_status_snapshot();
            } else {
                plugin_logger_warn(&g_logger,
                    "Could not acquire SOEM access for recovery (PLC not responding?)");
            }
        }

        /* Sleep for the monitor interval */
        struct timespec sleep_ts;
        sleep_ts.tv_sec = ECAT_MONITOR_INTERVAL_MS / 1000;
        sleep_ts.tv_nsec = (ECAT_MONITOR_INTERVAL_MS % 1000) * 1000000L;
        nanosleep(&sleep_ts, NULL);
    }

    plugin_logger_info(&g_logger, "EtherCAT monitor thread exiting");
    return NULL;
}
#endif /* ECAT_ENABLE_MONITOR_THREAD */

/*
 * =============================================================================
 * Plugin Lifecycle Functions
 * =============================================================================
 */

/**
 * @brief Initialize the EtherCAT plugin
 */
int init(void *args)
{
    /* Initialize logger first (before we have runtime_args) */
    plugin_logger_init(&g_logger, "ETHERCAT", NULL);
    plugin_logger_info(&g_logger, "Initializing EtherCAT plugin...");

    if (!args) {
        plugin_logger_error(&g_logger, "init args is NULL");
        return -1;
    }

    /* Copy runtime args (critical - pointer is freed after init returns) */
    memcpy(&g_runtime_args, args, sizeof(plugin_runtime_args_t));

    /* Re-initialize logger with runtime_args for central logging */
    plugin_logger_init(&g_logger, "ETHERCAT", args);

    plugin_logger_info(&g_logger, "Buffer size: %d", g_runtime_args.buffer_size);

    /* Parse configuration file */
    const char *config_path = g_runtime_args.plugin_specific_config_file_path;
    if (config_path == NULL || config_path[0] == '\0') {
        plugin_logger_warn(&g_logger, "No config file specified, using defaults");
        ecat_config_init_defaults(&g_config);
    } else {
        plugin_logger_info(&g_logger, "Loading config: %s", config_path);
        int result = ecat_config_parse(config_path, &g_config);
        if (result != ECAT_CONFIG_OK) {
            plugin_logger_error(&g_logger, "Failed to parse config file (error %d)", result);
            plugin_logger_warn(&g_logger, "Using default configuration");
            ecat_config_init_defaults(&g_config);
        } else {
            plugin_logger_info(&g_logger, "Configuration loaded successfully");
        }
    }

    /* Log configuration summary */
    plugin_logger_info(&g_logger, "Master config: interface=%s, cycle_time=%d us, watchdog=%d cycles",
                       g_config.master.interface,
                       g_config.master.cycle_time_us,
                       g_config.master.watchdog_timeout_cycles);
    plugin_logger_info(&g_logger, "Slaves configured: %d", g_config.slave_count);

    for (int i = 0; i < g_config.slave_count; i++) {
        const ecat_slave_t *slave = &g_config.slaves[i];
        plugin_logger_info(&g_logger, "  Slave %d: %s (%s) vendor=0x%08X product=0x%08X channels=%d sdos=%d",
                           slave->position, slave->name, slave->type,
                           slave->vendor_id, slave->product_code,
                           slave->channel_count, slave->sdo_count);
    }

    /* Initialize status and diagnostics */
    memset(&g_status_snapshot, 0, sizeof(g_status_snapshot));
    memset(&g_diag, 0, sizeof(g_diag));

    atomic_store(&g_plugin_state, ECAT_STATE_IDLE);
    plugin_logger_info(&g_logger, "EtherCAT plugin initialized [state: IDLE]");

    return 0;
}

/**
 * @brief Start the EtherCAT master with explicit state transitions
 *
 * Sequence: SCANNING -> CONFIGURING -> TRANSITIONING -> OPERATIONAL
 */
int start_loop(void)
{
    int state = atomic_load(&g_plugin_state);
    if (state != ECAT_STATE_IDLE && state != ECAT_STATE_STOPPED) {
        plugin_logger_error(&g_logger, "Cannot start - invalid state: %s",
                            ecat_state_to_string(state));
        return -1;
    }

    if (g_config.slave_count == 0) {
        plugin_logger_warn(&g_logger, "No slaves configured - EtherCAT master will not start");
        return -1;
    }

    /* --- Phase 1: SCANNING --- */
    atomic_store(&g_plugin_state, ECAT_STATE_SCANNING);
    plugin_logger_info(&g_logger, "[state: SCANNING] Opening interface and scanning bus...");

    if (ecat_master_open_and_scan(&g_config, &g_logger) != 0) {
        plugin_logger_error(&g_logger, "Bus scan failed");
        atomic_store(&g_plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* --- Phase 2: CONFIGURING (SDO writes + PDO mapping) --- */
    atomic_store(&g_plugin_state, ECAT_STATE_CONFIGURING);
    plugin_logger_info(&g_logger, "[state: CONFIGURING] Writing SDOs and mapping process data...");

    /* Write SDOs for each slave that has them configured */
    for (int i = 0; i < g_config.slave_count; i++) {
        const ecat_slave_t *slave = &g_config.slaves[i];
        if (slave->sdo_count > 0) {
            ecat_master_write_sdos(slave->position, slave->sdo_configs,
                                   slave->sdo_count,
                                   slave->timeouts.sdo_timeout_ms, &g_logger);
        }
    }

    /* Map process data and configure DC */
    if (ecat_master_configure(&g_config, &g_logger) != 0) {
        plugin_logger_error(&g_logger, "Process data mapping failed");
        ecat_master_close(&g_logger);
        atomic_store(&g_plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* Build channel map for process data exchange */
    ecat_io_build_channel_map(&g_config, &g_channel_map, &g_runtime_args, &g_logger);

    /* Build pre-resolved transfer list for fast per-cycle I/O */
    ecat_io_build_transfer_list(&g_channel_map, &g_transfer_list, &g_runtime_args, &g_logger);

    /* Cache expected WKC */
    g_expected_wkc = ecat_master_get_expected_wkc();
    plugin_logger_info(&g_logger, "Expected WKC: %d", g_expected_wkc);

    g_receive_timeout_us = g_config.master.receive_timeout_us;
    if (g_receive_timeout_us < ECAT_MIN_RECEIVE_TIMEOUT_US)
        g_receive_timeout_us = ECAT_MIN_RECEIVE_TIMEOUT_US;
    plugin_logger_info(&g_logger, "Receive timeout: %d us (cycle_time=%d us)",
                       g_receive_timeout_us, g_config.master.cycle_time_us);

    /* --- Phase 3: TRANSITIONING --- */
    atomic_store(&g_plugin_state, ECAT_STATE_TRANSITIONING);
    plugin_logger_info(&g_logger, "[state: TRANSITIONING] Moving slaves to OPERATIONAL...");

    if (ecat_master_transition_to_op(&g_config, &g_logger) != 0) {
        plugin_logger_error(&g_logger, "Failed to reach OPERATIONAL state");
        ecat_master_close(&g_logger);
        atomic_store(&g_plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* --- Phase 4: OPERATIONAL --- */
    g_consecutive_wkc_errors = 0;
    g_recovery_attempts = 0;
    g_cycle_counter = 0;
    memset(&g_diag, 0, sizeof(g_diag));

    atomic_store(&g_plugin_state, ECAT_STATE_OPERATIONAL);

    /* Send one initial exchange to populate the IOmap with slave data */
    ecat_master_exchange_processdata(g_receive_timeout_us);

    update_status_snapshot();

#if ECAT_ENABLE_MONITOR_THREAD
    /* Start background monitor thread for state checks and recovery */
    atomic_store(&g_soem_pause_requested, false);
    atomic_store(&g_soem_paused, false);
    atomic_store(&g_exchange_skips, 0);
    atomic_store(&g_monitor_running, true);

    if (pthread_create(&g_monitor_thread, NULL, ecat_monitor_thread, NULL) != 0) {
        plugin_logger_warn(&g_logger,
            "Failed to create monitor thread - running without state monitoring");
        atomic_store(&g_monitor_running, false);
    }
#endif

    plugin_logger_info(&g_logger,
        "[state: OPERATIONAL] EtherCAT master started (synchronous exchange, "
        "monitor=%s)", ECAT_ENABLE_MONITOR_THREAD ? "enabled" : "disabled");

    return 0;
}

/**
 * @brief Stop the EtherCAT master
 */
void stop_loop(void)
{
    int state = atomic_load(&g_plugin_state);
    if (state == ECAT_STATE_STOPPED || state == ECAT_STATE_IDLE) {
        plugin_logger_debug(&g_logger, "EtherCAT master already stopped/idle");
        return;
    }

    plugin_logger_info(&g_logger, "Stopping EtherCAT master (current state: %s)...",
                       ecat_state_to_string(state));

#if ECAT_ENABLE_MONITOR_THREAD
    /* Stop the monitor thread before closing the master */
    if (atomic_load(&g_monitor_running)) {
        atomic_store(&g_monitor_running, false);
        pthread_join(g_monitor_thread, NULL);
        plugin_logger_debug(&g_logger, "Monitor thread joined");
    }
    atomic_store(&g_soem_pause_requested, false);
    atomic_store(&g_soem_paused, false);
#endif

    /* Log final diagnostics */
    if (g_diag.cycle_count > 0 || g_diag.wkc_error_count > 0) {
        uint64_t total_cycles = g_diag.cycle_count + g_diag.wkc_error_count;
        uint64_t avg_us = g_diag.cycle_count > 0
            ? (g_diag.sum_total_ns / g_diag.cycle_count) / 1000 : 0;
        plugin_logger_info(&g_logger,
            "Final cycle stats: %llu total (%llu ok, %llu errors), "
            "avg=%llu us, max_total=%llu us, max_exchange=%llu us",
            (unsigned long long)total_cycles,
            (unsigned long long)g_diag.cycle_count,
            (unsigned long long)g_diag.wkc_error_count,
            (unsigned long long)avg_us,
            (unsigned long long)(g_diag.max_total_ns / 1000),
            (unsigned long long)(g_diag.max_exchange_ns / 1000));
    }

    memset(&g_channel_map, 0, sizeof(g_channel_map));
    memset(&g_transfer_list, 0, sizeof(g_transfer_list));
    g_consecutive_wkc_errors = 0;
    g_recovery_attempts = 0;
    g_expected_wkc = 0;

    ecat_master_close(&g_logger);
    atomic_store(&g_plugin_state, ECAT_STATE_STOPPED);

    update_status_snapshot();
    plugin_logger_info(&g_logger, "[state: STOPPED] EtherCAT master stopped");
}

/**
 * @brief Cleanup plugin resources
 */
void cleanup(void)
{
    plugin_logger_info(&g_logger, "Cleaning up EtherCAT plugin...");

    int state = atomic_load(&g_plugin_state);
    if (state != ECAT_STATE_STOPPED && state != ECAT_STATE_IDLE) {
        stop_loop();
    }

    atomic_store(&g_plugin_state, ECAT_STATE_STOPPED);

    pthread_mutex_destroy(&g_status_mutex);

    plugin_logger_info(&g_logger, "EtherCAT plugin cleanup complete");
}

/**
 * @brief Called at the start of each PLC scan cycle
 *
 * Performs synchronous EtherCAT process data exchange:
 *   1. Writes PLC outputs (from previous cycle) into the real IOmap
 *   2. Exchanges process data with all slaves via SOEM
 *   3. Reads received inputs from the IOmap into PLC input buffers
 *   4. Tracks WKC errors (no blocking SOEM calls)
 *
 * All blocking operations (state checks, recovery) run in the background
 * monitor thread when ECAT_ENABLE_MONITOR_THREAD is enabled.
 */
void cycle_start(void)
{
    int state = atomic_load(&g_plugin_state);
    if (state != ECAT_STATE_OPERATIONAL && state != ECAT_STATE_RECOVERING)
        return;

    uint8_t *iomap = ecat_master_get_iomap();
    if (!iomap)
        return;

#if ECAT_ENABLE_MONITOR_THREAD
    /* If the monitor thread needs exclusive SOEM access, yield this cycle.
     * The PLC keeps running with stale I/O data for one cycle (~us). */
    if (atomic_load(&g_soem_pause_requested)) {
        atomic_store(&g_soem_paused, true);
        atomic_fetch_add(&g_exchange_skips, 1);
        return;
    }
#endif

    /* 1. Write PLC outputs to IOmap (from previous cycle's computation) */
    ecat_io_write_outputs_fast(&g_transfer_list, iomap);

    /* 2. Exchange process data with slaves (synchronous) */
    ec_timet t0, t1;
    osal_get_monotonic_time(&t0);
    int wkc = ecat_master_exchange_processdata(g_receive_timeout_us);
    osal_get_monotonic_time(&t1);

    g_diag.exchange_ns = elapsed_ns(&t0, &t1);

    /* 3. Read received inputs into PLC buffers */
    ecat_io_read_inputs_fast(&g_transfer_list, iomap);

    g_cycle_counter++;

    /* 4. WKC error tracking (no blocking SOEM calls) */
    if (wkc < g_expected_wkc) {
        g_consecutive_wkc_errors++;
        g_diag.wkc_error_count++;
        if (wkc == EC_NOFRAME)
            g_diag.noframe_count++;

        if (g_consecutive_wkc_errors == 1 ||
            (g_consecutive_wkc_errors % 100) == 0) {
            plugin_logger_warn(&g_logger,
                "WKC error: expected %d, got %d (consecutive: %d, "
                "exchange=%llu us)",
                g_expected_wkc, wkc, g_consecutive_wkc_errors,
                (unsigned long long)(g_diag.exchange_ns / 1000));
        }

#if ECAT_ENABLE_MONITOR_THREAD
        /* Trigger recovery (handled by monitor thread) */
        if (state == ECAT_STATE_OPERATIONAL &&
            g_consecutive_wkc_errors >= ECAT_WKC_ERROR_THRESHOLD) {
            plugin_logger_warn(&g_logger,
                "WKC error threshold (%d) reached, switching to RECOVERING",
                ECAT_WKC_ERROR_THRESHOLD);
            atomic_store(&g_plugin_state, ECAT_STATE_RECOVERING);
        }
#endif
    } else {
        g_consecutive_wkc_errors = 0;
    }

    /* 5. Update diagnostics (no SOEM calls) */
    g_diag.total_ns = g_diag.exchange_ns;
    g_diag.cycle_count++;
    g_diag.sum_total_ns += g_diag.total_ns;

    if (g_diag.exchange_ns > g_diag.max_exchange_ns)
        g_diag.max_exchange_ns = g_diag.exchange_ns;
    if (g_diag.total_ns > g_diag.max_total_ns)
        g_diag.max_total_ns = g_diag.total_ns;

    /* 6. Periodic diagnostic log */
    if ((g_diag.cycle_count % ECAT_DIAG_REPORT_INTERVAL) == 0 &&
        g_diag.cycle_count > 0) {
        uint64_t total_cycles = g_diag.cycle_count + g_diag.wkc_error_count;
        uint64_t avg_us = (g_diag.sum_total_ns / g_diag.cycle_count) / 1000;
        plugin_logger_info(&g_logger,
            "Cycle stats (%llu total): avg=%llu us, max_total=%llu us, "
            "max_exchange=%llu us",
            (unsigned long long)total_cycles,
            (unsigned long long)avg_us,
            (unsigned long long)(g_diag.max_total_ns / 1000),
            (unsigned long long)(g_diag.max_exchange_ns / 1000));
        plugin_logger_info(&g_logger,
            "WKC errors: %llu total, %llu noframe, rate=%.1f%%",
            (unsigned long long)g_diag.wkc_error_count,
            (unsigned long long)g_diag.noframe_count,
            total_cycles > 0
                ? (g_diag.wkc_error_count * 100.0 / total_cycles) : 0.0);

        /* Reset accumulators to prevent overflow on long runs */
        g_diag.sum_total_ns = 0;
        g_diag.cycle_count = 0;
        g_diag.wkc_error_count = 0;
        g_diag.noframe_count = 0;
        g_diag.max_exchange_ns = 0;
        g_diag.max_total_ns = 0;
    }
}

/**
 * @brief Called at the end of each PLC scan cycle
 *
 * Output data is written to the IOmap at the beginning of cycle_start()
 * (before the exchange), so this hook is intentionally a no-op.
 */
void cycle_end(void)
{
    /* Outputs are written at the start of the next cycle_start() so they
     * are sent in the same SOEM exchange that receives fresh inputs. */
}

/*
 * =============================================================================
 * Async Command Handling (execute_command)
 * =============================================================================
 */

/**
 * @brief Validate a network interface name for safe use in SOEM calls.
 *
 * Accepts Linux names (e.g. "eth0") and Windows NPF device paths
 * (e.g. "\\Device\\NPF_{GUID}").  Writes a JSON error to @p response
 * on failure.
 *
 * @return 0 if valid, -1 if invalid (response already filled)
 */
static int validate_interface_name(const char *ifname, char *response, size_t response_size)
{
    size_t ifname_len = strlen(ifname);
    if (ifname_len == 0 || ifname_len >= ECAT_IFNAME_MAX) {
        snprintf(response, response_size, "{\"error\":\"invalid interface name length\"}");
        return -1;
    }
    for (size_t i = 0; i < ifname_len; i++) {
        unsigned char c = (unsigned char)ifname[i];
        if (!isalnum(c) && c != '_' && c != '-' && c != '\\' && c != '{' && c != '}' && c != '.') {
            snprintf(response, response_size, "{\"error\":\"invalid interface name format\"}");
            return -1;
        }
    }
    return 0;
}

/**
 * @brief Handle the "scan" command using a temporary SOEM context
 *
 * Creates a separate ecx_contextt (not the master's g_ecx_context) to scan
 * the bus for slaves. This allows scanning even when the master is not running.
 */
static int handle_scan_command(cJSON *root, char *response, size_t response_size)
{
    cJSON *params = cJSON_GetObjectItemCaseSensitive(root, "params");
    cJSON *iface = params ? cJSON_GetObjectItemCaseSensitive(params, "interface") : NULL;

    if (!iface || !cJSON_IsString(iface)) {
        snprintf(response, response_size, "{\"error\":\"missing 'interface' param\"}");
        return -1;
    }

    if (validate_interface_name(iface->valuestring, response, response_size) != 0)
        return -1;

    /* Refuse scan while master is actively running on the bus */
    int state = atomic_load(&g_plugin_state);
    if (state == ECAT_STATE_OPERATIONAL || state == ECAT_STATE_RECOVERING ||
        state == ECAT_STATE_TRANSITIONING) {
        snprintf(response, response_size,
            "{\"error\":\"EtherCAT master is running. Stop the PLC before scanning.\"}");
        return -1;
    }

    /* Temporary SOEM context for scan (independent from the master context) */
    ecx_contextt scan_ctx;
    memset(&scan_ctx, 0, sizeof(scan_ctx));

    if (!ecx_init(&scan_ctx, iface->valuestring)) {
        snprintf(response, response_size,
            "{\"error\":\"Failed to open interface '%s'\"}", iface->valuestring);
        return -1;
    }

    int slave_count = ecx_config_init(&scan_ctx);
    if (slave_count <= 0) {
        ecx_close(&scan_ctx);
        snprintf(response, response_size,
            "{\"status\":\"success\",\"devices\":[],\"message\":\"No slaves found\",\"slave_count\":0}");
        return 0;
    }

    /* Build JSON response with discovered slaves */
    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON *devices = cJSON_AddArrayToObject(resp, "devices");

    for (int i = 1; i <= scan_ctx.slavecount; i++) {
        ec_slavet *s = &scan_ctx.slavelist[i];
        cJSON *dev = cJSON_CreateObject();
        cJSON_AddNumberToObject(dev, "position", i);
        cJSON_AddStringToObject(dev, "name", s->name);
        cJSON_AddNumberToObject(dev, "vendor_id", s->eep_man);
        cJSON_AddNumberToObject(dev, "product_code", s->eep_id);
        cJSON_AddNumberToObject(dev, "revision", s->eep_rev);
        cJSON_AddNumberToObject(dev, "serial_number", s->eep_ser);
        cJSON_AddStringToObject(dev, "state", "UNKNOWN");
        cJSON_AddNumberToObject(dev, "al_status_code", 0);
        cJSON_AddBoolToObject(dev, "has_coe", (s->mbx_proto & 0x04) != 0);
        cJSON_AddNumberToObject(dev, "input_bytes", 0);
        cJSON_AddNumberToObject(dev, "output_bytes", 0);
        cJSON_AddItemToArray(devices, dev);
    }

    char msg[128];
    snprintf(msg, sizeof(msg), "Found %d EtherCAT slave(s)", scan_ctx.slavecount);
    cJSON_AddStringToObject(resp, "message", msg);
    cJSON_AddNumberToObject(resp, "slave_count", scan_ctx.slavecount);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    ecx_close(&scan_ctx);
    return 0;
}

/**
 * @brief Handle the "list-interfaces" command
 *
 * Uses ec_find_adapters() from SOEM to enumerate network adapters.
 * Does not require a SOEM context or bus access.
 */
static int handle_list_interfaces_command(char *response, size_t response_size)
{
    ec_adaptert *adapters = ec_find_adapters();

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON *ifaces = cJSON_AddArrayToObject(resp, "interfaces");

    int count = 0;
    for (ec_adaptert *a = adapters; a != NULL; a = a->next) {
        cJSON *entry = cJSON_CreateObject();
        cJSON_AddStringToObject(entry, "name", a->name);
        cJSON_AddStringToObject(entry, "description", a->desc);
        cJSON_AddItemToArray(ifaces, entry);
        count++;
    }

    char msg[64];
    snprintf(msg, sizeof(msg), "Found %d network interface(s)", count);
    cJSON_AddStringToObject(resp, "message", msg);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);
    ec_free_adapters(adapters);

    return 0;
}

/**
 * @brief Handle the "test" command using a temporary SOEM context
 *
 * Creates a separate ecx_contextt to scan the bus and return info about
 * the slave at the requested position. Used by the Editor to test
 * connectivity to a specific device.
 */
static int handle_test_command(cJSON *root, char *response, size_t response_size)
{
    cJSON *params = cJSON_GetObjectItemCaseSensitive(root, "params");
    cJSON *iface = params ? cJSON_GetObjectItemCaseSensitive(params, "interface") : NULL;
    cJSON *pos = params ? cJSON_GetObjectItemCaseSensitive(params, "position") : NULL;

    if (!iface || !cJSON_IsString(iface)) {
        snprintf(response, response_size, "{\"error\":\"missing 'interface' param\"}");
        return -1;
    }
    if (!pos || !cJSON_IsNumber(pos)) {
        snprintf(response, response_size, "{\"error\":\"missing 'position' param\"}");
        return -1;
    }

    int position = pos->valueint;
    if (position < 1) {
        snprintf(response, response_size, "{\"error\":\"'position' must be a positive integer\"}");
        return -1;
    }

    if (validate_interface_name(iface->valuestring, response, response_size) != 0)
        return -1;

    /* Refuse test while master is actively running on the bus */
    int state = atomic_load(&g_plugin_state);
    if (state == ECAT_STATE_OPERATIONAL || state == ECAT_STATE_RECOVERING ||
        state == ECAT_STATE_TRANSITIONING) {
        snprintf(response, response_size,
            "{\"error\":\"EtherCAT master is running. Stop the PLC before testing.\"}");
        return -1;
    }

    ecx_contextt test_ctx;
    memset(&test_ctx, 0, sizeof(test_ctx));

    if (!ecx_init(&test_ctx, iface->valuestring)) {
        snprintf(response, response_size,
            "{\"error\":\"Failed to open interface '%s'\"}", iface->valuestring);
        return -1;
    }

    int slave_count = ecx_config_init(&test_ctx);
    if (slave_count <= 0) {
        ecx_close(&test_ctx);
        snprintf(response, response_size,
            "{\"status\":\"success\",\"connected\":false,\"device\":null,"
            "\"message\":\"No EtherCAT slaves found on the network\"}");
        return 0;
    }

    if (position > test_ctx.slavecount) {
        char msg[128];
        snprintf(msg, sizeof(msg),
            "No device at position %d. Found %d slave(s).",
            position, test_ctx.slavecount);
        ecx_close(&test_ctx);
        snprintf(response, response_size,
            "{\"status\":\"error\",\"connected\":false,\"device\":null,"
            "\"message\":\"%s\"}", msg);
        return -1;
    }

    ec_slavet *s = &test_ctx.slavelist[position];

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON_AddBoolToObject(resp, "connected", 1);

    cJSON *dev = cJSON_CreateObject();
    cJSON_AddNumberToObject(dev, "position", position);
    cJSON_AddStringToObject(dev, "name", s->name);
    cJSON_AddNumberToObject(dev, "vendor_id", s->eep_man);
    cJSON_AddNumberToObject(dev, "product_code", s->eep_id);
    cJSON_AddNumberToObject(dev, "revision", s->eep_rev);
    cJSON_AddNumberToObject(dev, "serial_number", s->eep_ser);
    cJSON_AddStringToObject(dev, "state", "UNKNOWN");
    cJSON_AddNumberToObject(dev, "al_status_code", 0);
    cJSON_AddBoolToObject(dev, "has_coe", (s->mbx_proto & 0x04) != 0);
    cJSON_AddNumberToObject(dev, "input_bytes", 0);
    cJSON_AddNumberToObject(dev, "output_bytes", 0);
    cJSON_AddItemToObject(resp, "device", dev);

    char msg[128];
    snprintf(msg, sizeof(msg),
        "Successfully connected to %s at position %d", s->name, position);
    cJSON_AddStringToObject(resp, "message", msg);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    ecx_close(&test_ctx);
    return 0;
}

/**
 * @brief Handle the "status" command
 *
 * Returns a snapshot of the master status including plugin state,
 * per-slave states, and cycle metrics.
 */
static int handle_status_command(char *response, size_t response_size)
{
    ecat_master_status_t snap;

    pthread_mutex_lock(&g_status_mutex);
    memcpy(&snap, &g_status_snapshot, sizeof(snap));
    pthread_mutex_unlock(&g_status_mutex);

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "plugin_state",
                            ecat_state_to_string(snap.plugin_state));
    cJSON_AddNumberToObject(resp, "slave_count", snap.slave_count);
    cJSON_AddNumberToObject(resp, "expected_wkc", snap.expected_wkc);

    /* Per-slave status */
    cJSON *slaves = cJSON_AddArrayToObject(resp, "slaves");
    for (int i = 0; i < snap.slave_count && i < ECAT_MAX_SLAVES; i++) {
        const ecat_slave_status_t *ss = &snap.slaves[i];
        cJSON *slave = cJSON_CreateObject();
        cJSON_AddNumberToObject(slave, "position", ss->position);
        cJSON_AddStringToObject(slave, "name", ss->name);
        cJSON_AddStringToObject(slave, "state", al_state_to_string(ss->al_state));
        cJSON_AddNumberToObject(slave, "al_status_code", ss->al_status_code);
        cJSON_AddNumberToObject(slave, "error_count", ss->error_count);
        cJSON_AddBoolToObject(slave, "has_error",
                              (ss->al_state & EC_STATE_ERROR) != 0 ||
                              ss->al_state != EC_STATE_OPERATIONAL);
        cJSON_AddItemToArray(slaves, slave);
    }

    /* Cycle metrics */
    cJSON *metrics = cJSON_CreateObject();
    cJSON_AddNumberToObject(metrics, "cycle_count", (double)snap.cycle_count);
    cJSON_AddNumberToObject(metrics, "wkc_error_count", (double)snap.wkc_error_count);
    cJSON_AddNumberToObject(metrics, "avg_cycle_us", (double)snap.avg_cycle_us);
    cJSON_AddNumberToObject(metrics, "max_cycle_us", (double)snap.max_cycle_us);
    cJSON_AddNumberToObject(metrics, "max_exchange_us", (double)snap.max_exchange_us);
    cJSON_AddNumberToObject(metrics, "consecutive_wkc_errors", snap.consecutive_wkc_errors);
    cJSON_AddNumberToObject(metrics, "recovery_attempts", snap.recovery_attempts);
    cJSON_AddNumberToObject(metrics, "exchange_skips", (double)snap.exchange_skips);
    cJSON_AddItemToObject(resp, "metrics", metrics);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    return 0;
}

/**
 * @brief Handle the "diagnostics" command
 *
 * Returns detailed diagnostic information including per-slave error
 * breakdown and extended timing data.
 */
static int handle_diagnostics_command(char *response, size_t response_size)
{
    ecat_master_status_t snap;

    pthread_mutex_lock(&g_status_mutex);
    memcpy(&snap, &g_status_snapshot, sizeof(snap));
    pthread_mutex_unlock(&g_status_mutex);

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "plugin_state",
                            ecat_state_to_string(snap.plugin_state));
    cJSON_AddNumberToObject(resp, "slave_count", snap.slave_count);
    cJSON_AddNumberToObject(resp, "expected_wkc", snap.expected_wkc);

    /* Per-slave detailed status */
    cJSON *slaves = cJSON_AddArrayToObject(resp, "slaves");
    for (int i = 0; i < snap.slave_count && i < ECAT_MAX_SLAVES; i++) {
        const ecat_slave_status_t *ss = &snap.slaves[i];
        cJSON *slave = cJSON_CreateObject();
        cJSON_AddNumberToObject(slave, "position", ss->position);
        cJSON_AddStringToObject(slave, "name", ss->name);
        cJSON_AddStringToObject(slave, "state", al_state_to_string(ss->al_state));
        cJSON_AddNumberToObject(slave, "al_state_raw", ss->al_state);
        cJSON_AddNumberToObject(slave, "al_status_code", ss->al_status_code);
        cJSON_AddNumberToObject(slave, "error_count", ss->error_count);
        cJSON_AddBoolToObject(slave, "has_error",
                              (ss->al_state & EC_STATE_ERROR) != 0 ||
                              ss->al_state != EC_STATE_OPERATIONAL);
        cJSON_AddItemToArray(slaves, slave);
    }

    /* Extended timing metrics */
    cJSON *timing = cJSON_CreateObject();
    cJSON_AddNumberToObject(timing, "cycle_count", (double)snap.cycle_count);
    cJSON_AddNumberToObject(timing, "wkc_error_count", (double)snap.wkc_error_count);
    cJSON_AddNumberToObject(timing, "avg_cycle_us", (double)snap.avg_cycle_us);
    cJSON_AddNumberToObject(timing, "max_cycle_us", (double)snap.max_cycle_us);
    cJSON_AddNumberToObject(timing, "max_exchange_us", (double)snap.max_exchange_us);
    cJSON_AddNumberToObject(timing, "configured_cycle_us", g_config.master.cycle_time_us);
    cJSON_AddNumberToObject(timing, "receive_timeout_us", g_receive_timeout_us);
    cJSON_AddItemToObject(resp, "timing", timing);

    /* Recovery info */
    cJSON *recovery = cJSON_CreateObject();
    cJSON_AddNumberToObject(recovery, "consecutive_wkc_errors", snap.consecutive_wkc_errors);
    cJSON_AddNumberToObject(recovery, "recovery_attempts", snap.recovery_attempts);
    cJSON_AddNumberToObject(recovery, "max_recovery_attempts", ECAT_MAX_RECOVERY_ATTEMPTS);
    cJSON_AddNumberToObject(recovery, "wkc_error_threshold", ECAT_WKC_ERROR_THRESHOLD);
    cJSON_AddNumberToObject(recovery, "exchange_skips", (double)snap.exchange_skips);
    cJSON_AddItemToObject(resp, "recovery", recovery);

    /* Master configuration */
    cJSON *master_cfg = cJSON_CreateObject();
    cJSON_AddStringToObject(master_cfg, "interface", g_config.master.interface);
    cJSON_AddNumberToObject(master_cfg, "cycle_time_us", g_config.master.cycle_time_us);
    cJSON_AddNumberToObject(master_cfg, "watchdog_timeout_cycles",
                            g_config.master.watchdog_timeout_cycles);
    cJSON_AddItemToObject(resp, "master_config", master_cfg);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    return 0;
}

/**
 * @brief Execute an async command routed from the unix socket
 */
int execute_command(const char *command_json, char *response, size_t response_size)
{
    cJSON *root = cJSON_Parse(command_json);
    if (!root) {
        snprintf(response, response_size, "{\"error\":\"invalid JSON\"}");
        return -1;
    }

    cJSON *cmd = cJSON_GetObjectItemCaseSensitive(root, "command");
    if (!cmd || !cJSON_IsString(cmd)) {
        cJSON_Delete(root);
        snprintf(response, response_size, "{\"error\":\"missing 'command' field\"}");
        return -1;
    }

    int result = -1;
    if (strcmp(cmd->valuestring, "scan") == 0) {
        result = handle_scan_command(root, response, response_size);
    } else if (strcmp(cmd->valuestring, "list-interfaces") == 0) {
        result = handle_list_interfaces_command(response, response_size);
    } else if (strcmp(cmd->valuestring, "test") == 0) {
        result = handle_test_command(root, response, response_size);
    } else if (strcmp(cmd->valuestring, "status") == 0) {
        result = handle_status_command(response, response_size);
    } else if (strcmp(cmd->valuestring, "diagnostics") == 0) {
        result = handle_diagnostics_command(response, response_size);
    } else {
        snprintf(response, response_size, "{\"error\":\"unknown command '%s'\"}", cmd->valuestring);
    }

    cJSON_Delete(root);
    return result;
}
